### ISSUE TITLE
how to train the Snips server?

### ISSUE THREAD

**Issue by jBernavaPrah** [jovotech/snips-nlu-server#3]
Hi @jankoenig @aswetlow @rubenaeg.

QQ: how may I train the Snips server? 
I saw that there is an endpoint `/engine/train`, but there is no clear guide on how to call it. 

I'm trying to test it using Jovo v4 with a JovoDebugger platform.

Thanks a lot,
Jure,

**Comment by jBernavaPrah** [comment]
The question come from the error that I get from the server:

```
ERROR:server:Exception on /engine/parse [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 223, in __call__
    return call_result.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 292, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/app/server.py", line 74, in parse_message
    result = parse_from_engine(path.join(engine_directory, 'engine'))
  File "/app/server.py", line 116, in parse_from_engine
    engine: SnipsNLUEngine = SnipsNLUEngine.from_path(engine_path)
  File "/usr/local/lib/python3.8/site-packages/snips_nlu/nlu_engine/nlu_engine.py", line 347, in from_path
    raise LoadingError("Missing nlu engine model file: %s"
snips_nlu.exceptions.LoadingError: Missing nlu engine model file: nlu_engine.json
```
